---
# vars file for roles/backend-migrate
db_name: ansible
db_host: localhost
db_user: riyanda
db_port: 3306
db_pass: "{{ (lookup('file', '../../../vault.yml') | from_yaml).db_password | default('') }}"
mysql_root_user: "{{ (lookup('file', '../../../vault.yml') | from_yaml).mysql_root_user | default('') }}"
mysql_root_password: "{{ (lookup('file', '../../../vault.yml') | from_yaml).mysql_root_password | default('') }}"
