---
# tasks file for roles/backend-build
- name: Load variables from vault.yml
  include_vars:
    file: ../../../vault.yml

- name: Add PHP repo
  become: true
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update
  become: true
  apt:
    update_cache: yes

- name: Install PHP and related packages
  become: true
  apt:
    name:
      - php8.3-common
      - php8.3-cli
      - php8.3-mbstring
      - php8.3-xml
      - unzip
      - php8.3-curl
      - php8.3-mysql
      - php8.3-fpm
      - php8.3-intl
      - curl
      - openssl
      - ca-certificates
      - zlib1g
    state: present
    update_cache: yes

- name: Add safe directory for Git
  community.general.git_config:
    name: safe.directory
    value: /var/www/be-todo
    scope: global

- name: Clone Repo BE
  git:
    repo: https://github.com/elshiraphine/be-todo.git
    dest: /var/www/be-todo
    version: master
    force: yes

- name: Change permission
  file:
    path: /var/www/be-todo
    mode: "0775"
    recurse: yes
  become: true

- name: Change permission 2
  file:
    path: /usr/local/bin
    mode: "0777"
    recurse: yes
  become: true

- name: Change ownership
  file:
    path: /var/www/be-todo
    owner: www-data
    group: www-data
    recurse: yes
  become: true

- name: Ensure zlib is enabled in PHP
  shell: |
    if ! php -m | grep -q 'zlib'; then
      echo "zlib is not enabled. Please enable it in your PHP configuration."
      exit 1
    fi

- name: Ensure openssl is enabled in PHP
  shell: |
    if ! php -m | grep -q 'openssl'; then
      echo "openssl is not enabled. Please enable it in your PHP configuration."
      exit 1
    fi

- name: Download Composer installer using alternative method
  get_url:
    url: https://getcomposer.org/installer
    dest: /var/www/be-todo/composer-setup.php
    mode: "0755"
    timeout: 60
  become: true

- name: Verify Composer installer
  shell: "php composer-setup.php --check"
  args:
    chdir: /var/www/be-todo
  register: composer_verify

- name: Install Composer
  command: "php composer-setup.php --install-dir=/usr/local/bin --filename=composer"
  args:
    chdir: /var/www/be-todo
  when: composer_verify.rc == 0

- name: Remove Composer installer
  command: "rm composer-setup.php"
  args:
    chdir: /var/www/be-todo

- name: Remove composer.lock file
  command: "rm composer.lock"
  args:
    chdir: /var/www/be-todo
  become: true

- name: Update Composer Dependencies as root
  community.general.composer:
    command: update
    working_dir: /var/www/be-todo
    arguments: "--no-plugins --no-scripts"
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Install Composer Dependencies as root
  community.general.composer:
    command: install
    working_dir: /var/www/be-todo
    arguments: "--no-plugins --no-scripts"
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Copy env
  become: true
  copy:
    src: templates/env-template
    dest: /var/www/be-todo/.env

- name: Configure Laravel database
  template:
    src: templates/env-template
    dest: /var/www/be-todo/.env
  vars:
    db_name: "{{  var_name }}"
    db_user: "{{  var_user }}"
    db_password: "{{  var_password }}"

- name: Run composer dump-autoload
  community.general.composer:
    command: dump-autoload
    working_dir: /var/www/be-todo
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Generate App Key
  shell: |
    cd /var/www/be-todo
    php artisan key:generate
  become: yes
