---
# tasks file for roles/backend-build

- name: Load variables from env/vars.yml
  include_vars:
    file: ../../../env/vars.yml

- name: Add PHP repo
  become: true
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update
  become: true
  apt:
    update_cache: yes

- name: Install PHP and related packages
  become: true
  apt:
    name:
      - php8.3-common
      - php8.3-cli
      - php8.3-mbstring
      - php8.3-xml
      - unzip
      - php8.3-curl
      - php8.3-mysql
      - php8.3-fpm
      - php8.3-intl
      - curl
      - openssl
      - ca-certificates
      - zlib1g
    state: present
    update_cache: yes
  notify: Restart PHP 8.3 FPM

- name: Add safe directory for Git
  community.general.git_config:
    name: safe.directory
    value: "{{ backend_dir }}"
    scope: global

- name: Clone Repo BE
  git:
    repo: "{{ backend_repo }}"
    dest: "{{ backend_dir }}"
    version: master
    force: yes

- name: Change permission
  file:
    path: "{{ backend_dir }}"
    mode: "0775"
    recurse: yes
  become: true

- name: Change permission 2
  file:
    path: /usr/local/bin
    mode: "0777"
    recurse: yes
  become: true

- name: Change ownership
  file:
    path: "{{ backend_dir }}"
    owner: www-data
    group: www-data
    recurse: yes
  become: true

- name: Download Composer installer using alternative method
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ backend_dir }}/composer-setup.php"
    mode: "0755"
    timeout: 60
  become: true

- name: Verify Composer installer
  shell: "php composer-setup.php --check"
  args:
    chdir: "{{ backend_dir }}"
  register: composer_verify

- name: Install Composer
  command: "php composer-setup.php --install-dir=/usr/local/bin --filename=composer"
  args:
    chdir: "{{ backend_dir }}"
  when: composer_verify.rc == 0

- name: Remove Composer installer
  command: "rm composer-setup.php"
  args:
    chdir: "{{ backend_dir }}"

- name: Remove composer.lock file
  command: "rm composer.lock"
  args:
    chdir: "{{ backend_dir }}"
  become: true

- name: Update Composer Dependencies as root
  community.general.composer:
    command: update
    working_dir: "{{ backend_dir }}"
    arguments: "--no-plugins --no-scripts"
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Install Composer Dependencies as root
  community.general.composer:
    command: install
    working_dir: "{{ backend_dir }}"
    arguments: "--no-plugins --no-scripts"
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"
  notify: Restart PHP 8.3 FPM

- name: Copy env
  become: true
  copy:
    src: templates/env-template
    dest: "{{ backend_dir }}/.env"

- name: Configure Laravel database
  template:
    src: templates/env-template
    dest: "{{ backend_dir }}/.env"
  vars:
    db_name: "{{  var_name }}"
    db_user: "{{  var_user }}"
    db_password: "{{  var_password }}"

- name: Run composer dump-autoload
  community.general.composer:
    command: dump-autoload
    working_dir: "{{ backend_dir }}"
  become: true
  become_user: root
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Generate App Key
  shell: |
    cd "{{ backend_dir }}"
    php artisan key:generate
  become: yes
  notify: Restart PHP 8.3 FPM
