---
# tasks file for backend-migrate
- name: Load variables from env/vars.yml
  include_vars:
    file: ../../../env/vars.yml

- name: Run PHP Artisan Migrate
  command:
    cmd: "php artisan migrate"
    chdir: "{{ backend_dir }}"

- name: Generate JWT Secret
  command:
    cmd: "php artisan jwt:secret"
    chdir: "{{ backend_dir }}"
