---
# tasks file for backend

- name: Run PHP Artisan Migrate
  command:
    cmd: "php artisan migrate"
    chdir: "/var/www/be-todo"

- name: Generate JWT Secret
  command:
    cmd: "php artisan jwt:secret"
    chdir: "/var/www/be-todo"
