---
# tasks file for roles/frontend-deploy
- name: Load variables from env/vars.yml
  include_vars:
    file: ../../../env/vars.yml

- name: Start frontend application using pm2
  shell: |
    cd "{{ frontend_dir }}"
    pm2 start --name fe-todo "yarn start"
  args:
    executable: /bin/bash
