# playbooks/main.yml
---
- import_playbook: prepare.yml
- import_playbook: build.yml
- import_playbook: migrate.yml
- import_playbook: deploy.yml

- name: Run playbook main
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - ../vault.yml
