---
# tasks file for roles/nginx-prepare

- name: Install the NGINX application on localhost
  package:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Delete default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx template
  template:
    src: nginx-template.j2
    dest: /etc/nginx/sites-available/frontend
  notify: Restart nginx
