---
# tasks file for roles/frontend-build
- name: Load variables from env/vars.yml
  include_vars:
    file: ../../../env/vars.yml

- name: Install dependencies for nvm
  apt:
    name:
      - curl
      - build-essential
      - libssl-dev
    state: present
    update_cache: yes

- name: Download and install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    executable: /bin/bash

- name: Add Yarn APT key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn APT repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Yarn
  apt:
    name: yarn
    state: present

- name: Ensure Yarn is installed
  command: yarn --version
  register: yarn_version

- name: Debug Yarn version
  debug:
    var: yarn_version.stdout

- name: Install Node.js version 20 using nvm
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install 20
    nvm alias default 20
  args:
    executable: /bin/bash
  environment:
    HOME: /root

- name: Ensure Node.js version 20 is installed
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    node --version
  args:
    executable: /bin/bash
  register: node_version

- name: Debug nvm version
  debug:
    var: node_version.stdout

- name: Install npm
  apt:
    name: npm
    state: present

- name: Install pm2 globally using npm
  npm:
    name: pm2
    global: yes

- name: Ensure pm2 is installed
  command: pm2 --version
  register: pm2_version

- name: Debug pm2 version
  debug:
    var: pm2_version.stdout

- name: Add safe directory for Git
  community.general.git_config:
    name: safe.directory
    value: /var/www/fe-todo
    scope: global

- name: Clone Repo FE
  git:
    repo: https://github.com/elshiraphine/fe-todo.git
    dest: /var/www/fe-todo
    version: main
    force: yes

- name: Change permission
  file:
    path: /var/www/fe-todo
    mode: "0777"
    recurse: yes
  become: true

- name: Change ownership
  file:
    path: "{{ frontend_dir }}"
    owner: www-data
    group: www-data
    recurse: yes
  become: true

- name: Change directory to /var/www/fe-todo and install dependencies
  shell: |
    cd "{{ frontend_dir }}"
    yarn install --ignore-engines
  args:
    executable: /bin/bash

- name: Update baseURL in config.ts using template
  become: true
  template:
    src: templates/config.ts.j2
    dest: "{{ frontend_dir }}/src/app/config/config.ts"
  vars:
    base_url: "http://localhost:9000/api"

- name: Build the project
  shell: |
    cd "{{ frontend_dir }}"
    yarn build
  args:
    executable: /bin/bash
